#ifndef ASSETS_H
#define ASSETS_H

#include "debug.h"
#include "graphics_manager.h"

#include <cstddef>

namespace castlekeep
{
namespace assets
{
struct AssetName {
	const char* data;
	const char* image;
};

constexpr static inline AssetName animation_assets[] = {
    {"data/graphics/anim_armourer.data", "data/graphics/anim_armourer.png"},
    {"data/graphics/anim_baker.data", "data/graphics/anim_baker.png"},
    {"data/graphics/anim_blacksmith.data", "data/graphics/anim_blacksmith.png"},
    {"data/graphics/anim_boiled_oil.data", "data/graphics/anim_boiled_oil.png"},
    {"data/graphics/anim_brewer.data", "data/graphics/anim_brewer.png"},
    {"data/graphics/anim_chopping_block.data",
     "data/graphics/anim_chopping_block.png"},
    {"data/graphics/anim_dungeon.data", "data/graphics/anim_dungeon.png"},
    {"data/graphics/anim_farmer.data", "data/graphics/anim_farmer.png"},
    {"data/graphics/anim_flags.data", "data/graphics/anim_flags.png"},
    {"data/graphics/anim_flag_small.data", "data/graphics/anim_flag_small.png"},
    {"data/graphics/anim_fletcher.data", "data/graphics/anim_fletcher.png"},
    {"data/graphics/anim_healer.data", "data/graphics/anim_healer.png"},
    {"data/graphics/anim_hunter.data", "data/graphics/anim_hunter.png"},
    {"data/graphics/anim_inn.data", "data/graphics/anim_inn.png"},
    {"data/graphics/anim_iron_miner.data", "data/graphics/anim_iron_miner.png"},
    {"data/graphics/anim_market.data", "data/graphics/anim_market.png"},
    {"data/graphics/anim_maypole.data", "data/graphics/anim_maypole.png"},
    {"data/graphics/anim_pitch_dugout.data",
     "data/graphics/anim_pitch_dugout.png"},
    {"data/graphics/anim_poleturner.data", "data/graphics/anim_poleturner.png"},
    {"data/graphics/anim_quarry.data", "data/graphics/anim_quarry.png"},
    {"data/graphics/anim_shields.data", "data/graphics/anim_shields.png"},
    {"data/graphics/anim_stables.data", "data/graphics/anim_stables.png"},
    {"data/graphics/anim_stake.data", "data/graphics/anim_stake.png"},
    {"data/graphics/anim_tanner.data", "data/graphics/anim_tanner.png"},
    {"data/graphics/anim_tunnels.data", "data/graphics/anim_tunnels.png"},
    {"data/graphics/anim_windmill.data", "data/graphics/anim_windmill.png"},
    {"data/graphics/anim_woodcutter.data", "data/graphics/anim_woodcutter.png"},
    {"data/graphics/body_animal_burning_big.data",
     "data/graphics/body_animal_burning_big.png"},
    {"data/graphics/body_animal_burning_small.data",
     "data/graphics/body_animal_burning_small.png"},
    {"data/graphics/body_archer.data", "data/graphics/body_archer.png"},
    {"data/graphics/body_armourer.data", "data/graphics/body_armourer.png"},
    {"data/graphics/body_baker.data", "data/graphics/body_baker.png"},
    {"data/graphics/body_ballista.data", "data/graphics/body_ballista.png"},
    {"data/graphics/body_battering_ram.data",
     "data/graphics/body_battering_ram.png"},
    {"data/graphics/body_bear.data", "data/graphics/body_bear.png"},
    {"data/graphics/body_blacksmith.data", "data/graphics/body_blacksmith.png"},
    {"data/graphics/body_boy.data", "data/graphics/body_boy.png"},
    {"data/graphics/body_brewer.data", "data/graphics/body_brewer.png"},
    {"data/graphics/body_catapult.data", "data/graphics/body_catapult.png"},
    {"data/graphics/body_chicken_brown.data",
     "data/graphics/body_chicken_brown.png"},
    {"data/graphics/body_chicken.data", "data/graphics/body_chicken.png"},
    {"data/graphics/body_cow.data", "data/graphics/body_cow.png"},
    {"data/graphics/body_crossbowman.data",
     "data/graphics/body_crossbowman.png"},
    {"data/graphics/body_crow.data", "data/graphics/body_crow.png"},
    {"data/graphics/body_deer.data", "data/graphics/body_deer.png"},
    {"data/graphics/body_dog.data", "data/graphics/body_dog.png"},
    {"data/graphics/body_drunkard.data", "data/graphics/body_drunkard.png"},
    {"data/graphics/body_farmer.data", "data/graphics/body_farmer.png"},
    {"data/graphics/body_fighting_monk.data",
     "data/graphics/body_fighting_monk.png"},
    {"data/graphics/body_fire_eater.data", "data/graphics/body_fire_eater.png"},
    {"data/graphics/body_fireman.data", "data/graphics/body_fireman.png"},
    {"data/graphics/body_fletcher.data", "data/graphics/body_fletcher.png"},
    {"data/graphics/body_ghost.data", "data/graphics/body_ghost.png"},
    {"data/graphics/body_girl.data", "data/graphics/body_girl.png"},
    {"data/graphics/body_healer.data", "data/graphics/body_healer.png"},
    {"data/graphics/body_horse_trader.data",
     "data/graphics/body_horse_trader.png"},
    {"data/graphics/body_hunter.data", "data/graphics/body_hunter.png"},
    {"data/graphics/body_innkeeper.data", "data/graphics/body_innkeeper.png"},
    {"data/graphics/body_iron_miner.data", "data/graphics/body_iron_miner.png"},
    {"data/graphics/body_jester.data", "data/graphics/body_jester.png"},
    {"data/graphics/body_juggler.data", "data/graphics/body_juggler.png"},
    {"data/graphics/body_knight.data", "data/graphics/body_knight.png"},
    {"data/graphics/body_knight_top.data", "data/graphics/body_knight_top.png"},
    {"data/graphics/body_ladder_bearer.data",
     "data/graphics/body_ladder_bearer.png"},
    {"data/graphics/body_lady.data", "data/graphics/body_lady.png"},
    {"data/graphics/body_lord.data", "data/graphics/body_lord.png"},
    {"data/graphics/body_maceman.data", "data/graphics/body_maceman.png"},
    {"data/graphics/body_man_burning.data",
     "data/graphics/body_man_burning.png"},
    {"data/graphics/body_mangonel.data", "data/graphics/body_mangonel.png"},
    {"data/graphics/body_miller.data", "data/graphics/body_miller.png"},
    {"data/graphics/body_missile_2.data", "data/graphics/body_missile_2.png"},
    {"data/graphics/body_missile_cow.data",
     "data/graphics/body_missile_cow.png"},
    {"data/graphics/body_missile.data", "data/graphics/body_missile.png"},
    {"data/graphics/body_missile_fire.data",
     "data/graphics/body_missile_fire.png"},
    {"data/graphics/body_mother.data", "data/graphics/body_mother.png"},
    {"data/graphics/body_ox.data", "data/graphics/body_ox.png"},
    {"data/graphics/body_peasant.data", "data/graphics/body_peasant.png"},
    {"data/graphics/body_pikeman.data", "data/graphics/body_pikeman.png"},
    {"data/graphics/body_pitch_worker.data",
     "data/graphics/body_pitch_worker.png"},
    {"data/graphics/body_poleturner.data", "data/graphics/body_poleturner.png"},
    {"data/graphics/body_priest.data", "data/graphics/body_priest.png"},
    {"data/graphics/body_rabbit.data", "data/graphics/body_rabbit.png"},
    {"data/graphics/body_seagull.data", "data/graphics/body_seagull.png"},
    {"data/graphics/body_shield.data", "data/graphics/body_shield.png"},
    {"data/graphics/body_siege_engineer.data",
     "data/graphics/body_siege_engineer.png"},
    {"data/graphics/body_siege_tower.data",
     "data/graphics/body_siege_tower.png"},
    {"data/graphics/body_spearman.data", "data/graphics/body_spearman.png"},
    {"data/graphics/body_splash.data", "data/graphics/body_splash.png"},
    {"data/graphics/body_stonemason.data", "data/graphics/body_stonemason.png"},
    {"data/graphics/body_swordsman.data", "data/graphics/body_swordsman.png"},
    {"data/graphics/body_tanner.data", "data/graphics/body_tanner.png"},
    {"data/graphics/body_tent.data", "data/graphics/body_tent.png"},
    {"data/graphics/body_trader.data", "data/graphics/body_trader.png"},
    {"data/graphics/body_trebutchet.data", "data/graphics/body_trebutchet.png"},
    {"data/graphics/body_tunnelor.data", "data/graphics/body_tunnelor.png"},
    {"data/graphics/body_wolf.data", "data/graphics/body_wolf.png"},
    {"data/graphics/body_woodcutter.data", "data/graphics/body_woodcutter.png"},
    {"data/graphics/tree_apple.data", "data/graphics/tree_apple.png"},
    {"data/graphics/tree_birch.data", "data/graphics/tree_birch.png"},
    {"data/graphics/Tree_Chestnut.data", "data/graphics/Tree_Chestnut.png"},
    {"data/graphics/tree_oak.data", "data/graphics/tree_oak.png"},
    {"data/graphics/tree_pine.data", "data/graphics/tree_pine.png"},
    {"data/graphics/tree_shrub1.data", "data/graphics/tree_shrub1.png"},
    {"data/graphics/tree_shrub2.data", "data/graphics/tree_shrub2.png"},

};

constexpr static inline AssetName tile_assets[] = {
    {"data/graphics/killing_pits.data", "data/graphics/killing_pits.png"},
    {"data/graphics/pitch_ditches.data", "data/graphics/pitch_ditches.png"},
    {"data/graphics/tile_buildings1.data", "data/graphics/tile_buildings1.png"},
    {"data/graphics/tile_buildings2.data", "data/graphics/tile_buildings2.png"},
    {"data/graphics/tile_burnt.data", "data/graphics/tile_burnt.png"},
    {"data/graphics/tile_castle.data", "data/graphics/tile_castle.png"},
    {"data/graphics/tile_churches.data", "data/graphics/tile_churches.png"},
    {"data/graphics/tile_data.data", "data/graphics/tile_data.png"},
    {"data/graphics/tile_farmland.data", "data/graphics/tile_farmland.png"},
    {"data/graphics/tile_flatties.data", "data/graphics/tile_flatties.png"},
    {"data/graphics/tile_goods.data", "data/graphics/tile_goods.png"},
    {"data/graphics/tile_land3.data", "data/graphics/tile_land3.png"},
    {"data/graphics/tile_land8.data", "data/graphics/tile_land8.png"},
    {"data/graphics/tile_land_and_stones.data",
     "data/graphics/tile_land_and_stones.png"},
    {"data/graphics/tile_land_macros.data",
     "data/graphics/tile_land_macros.png"},
    {"data/graphics/tile_rocks8.data", "data/graphics/tile_rocks8.png"},
    {"data/graphics/tile_ruins.data", "data/graphics/tile_ruins.png"},
    {"data/graphics/tile_sea8.data", "data/graphics/tile_sea8.png"},
    {"data/graphics/tile_sea_new_01.data", "data/graphics/tile_sea_new_01.png"},
    {"data/graphics/tile_workshops.data", "data/graphics/tile_workshops.png"},
};

constexpr static inline AssetName generic_image_assets[] = {
    {"data/graphics/anim_buildings2.data", "data/graphics/anim_buildings2.png"},
    {"data/graphics/anim_campaign_map_flags.data",
     "data/graphics/anim_campaign_map_flags.png"},
    {"data/graphics/anim_castle.data", "data/graphics/anim_castle.png"},
    {"data/graphics/anim_dancing_bear.data",
     "data/graphics/anim_dancing_bear.png"},
    {"data/graphics/anim_dog_cage.data", "data/graphics/anim_dog_cage.png"},
    {"data/graphics/anim_drawbridge.data", "data/graphics/anim_drawbridge.png"},
    {"data/graphics/anim_ducking_stool.data",
     "data/graphics/anim_ducking_stool.png"},
    {"data/graphics/anim_gallows.data", "data/graphics/anim_gallows.png"},
    {"data/graphics/anim_gibbet.data", "data/graphics/anim_gibbet.png"},
    {"data/graphics/anim_goods.data", "data/graphics/anim_goods.png"},
    {"data/graphics/anim_heads.data", "data/graphics/anim_heads.png"},
    {"data/graphics/anim_killing_pits.data",
     "data/graphics/anim_killing_pits.png"},
    {"data/graphics/anim_rack.data", "data/graphics/anim_rack.png"},
    {"data/graphics/anim_stocks.data", "data/graphics/anim_stocks.png"},
    {"data/graphics/anim_tunnelors_guild.data",
     "data/graphics/anim_tunnelors_guild.png"},
    {"data/graphics/anim_whitecaps.data", "data/graphics/anim_whitecaps.png"},
    {"data/graphics/army_units.data", "data/graphics/army_units.png"},
    {"data/graphics/blast3.data", "data/graphics/blast3.png"},
    {"data/graphics/body_brazier.data", "data/graphics/body_brazier.png"},
    {"data/graphics/body_disease.data", "data/graphics/body_disease.png"},
    {"data/graphics/body_fire2.data", "data/graphics/body_fire2.png"},
    {"data/graphics/body_fire.data", "data/graphics/body_fire.png"},
    {"data/graphics/body_gate.data", "data/graphics/body_gate.png"},
    {"data/graphics/body_steam.data", "data/graphics/body_steam.png"},
    {"data/graphics/cracks.data", "data/graphics/cracks.png"},
    {"data/graphics/cursors.data", "data/graphics/cursors.png"},
    {"data/graphics/enemy_faces.data", "data/graphics/enemy_faces.png"},
    {"data/graphics/float_pop_circ.data", "data/graphics/float_pop_circ.png"},
    {"data/graphics/floats.data", "data/graphics/floats.png"},
    {"data/graphics/floats_new.data", "data/graphics/floats_new.png"},
    {"data/graphics/font_slanted.data", "data/graphics/font_slanted.png"},
    {"data/graphics/font_stronghold_aa.data",
     "data/graphics/font_stronghold_aa.png"},
    {"data/graphics/font_stronghold.data", "data/graphics/font_stronghold.png"},
    {"data/graphics/icons_front_end_builder.data",
     "data/graphics/icons_front_end_builder.png"},
    {"data/graphics/icons_front_end_combat.data",
     "data/graphics/icons_front_end_combat.png"},
    {"data/graphics/icons_front_end.data", "data/graphics/icons_front_end.png"},
    {"data/graphics/icons_front_end_economics.data",
     "data/graphics/icons_front_end_economics.png"},
    {"data/graphics/icons_placeholders.data",
     "data/graphics/icons_placeholders.png"},
    {"data/graphics/interface_army.data", "data/graphics/interface_army.png"},
    {"data/graphics/interface_buttons.data",
     "data/graphics/interface_buttons.png"},
    {"data/graphics/interface_icons2.data",
     "data/graphics/interface_icons2.png"},
    {"data/graphics/interface_icons3.data",
     "data/graphics/interface_icons3.png"},
    {"data/graphics/interface_ruins.data", "data/graphics/interface_ruins.png"},
    {"data/graphics/interface_slider_bar.data",
     "data/graphics/interface_slider_bar.png"},
    {"data/graphics/mapedit_buttons.data", "data/graphics/mapedit_buttons.png"},
    {"data/graphics/mini_cursors.data", "data/graphics/mini_cursors.png"},
    {"data/graphics/oil_dropped.data", "data/graphics/oil_dropped.png"},
    {"data/graphics/rock_chips.data", "data/graphics/rock_chips.png"},
    {"data/graphics/scribe.data", "data/graphics/scribe.png"},
    {"data/graphics/smoke-30x30.data", "data/graphics/smoke-30x30.png"},
    {"data/graphics/tile_chevrons.data", "data/graphics/tile_chevrons.png"},
    {"data/graphics/tile_cliffs.data", "data/graphics/tile_cliffs.png"},
    {"data/graphics/tile_rocks_chevrons.data",
     "data/graphics/tile_rocks_chevrons.png"},
    {"data/graphics/tile_walls.data", "data/graphics/tile_walls.png"},
};

enum class AnimationID {
	anim_armourer = 0,
	anim_baker = 1,
	anim_blacksmith = 2,
	anim_boiled_oil = 3,
	anim_brewer = 4,
	anim_chopping_block = 5,
	anim_dungeon = 6,
	anim_farmer = 7,
	anim_flags = 8,
	anim_flag_small = 9,
	anim_fletcher = 10,
	anim_healer = 11,
	anim_hunter = 12,
	anim_inn = 13,
	anim_iron_miner = 14,
	anim_market = 15,
	anim_maypole = 16,
	anim_pitch_dugout = 17,
	anim_poleturner = 18,
	anim_quarry = 19,
	anim_shields = 20,
	anim_stables = 21,
	anim_stake = 22,
	anim_tanner = 23,
	anim_tunnels = 24,
	anim_windmill = 25,
	anim_woodcutter = 26,
	body_animal_burning_big = 27,
	body_animal_burning_small = 28,
	body_archer = 29,
	body_armourer = 30,
	body_baker = 31,
	body_ballista = 32,
	body_battering_ram = 33,
	body_bear = 34,
	body_blacksmith = 35,
	body_boy = 36,
	body_brewer = 37,
	body_catapult = 38,
	body_chicken_brown = 39,
	body_chicken = 40,
	body_cow = 41,
	body_crossbowman = 42,
	body_crow = 43,
	body_deer = 44,
	body_dog = 45,
	body_drunkard = 46,
	body_farmer = 47,
	body_fighting_monk = 48,
	body_fire_eater = 49,
	body_fireman = 50,
	body_fletcher = 51,
	body_ghost = 52,
	body_girl = 53,
	body_healer = 54,
	body_horse_trader = 55,
	body_hunter = 56,
	body_innkeeper = 57,
	body_iron_miner = 58,
	body_jester = 59,
	body_juggler = 60,
	body_knight = 61,
	body_knight_top = 62,
	body_ladder_bearer = 63,
	body_lady = 64,
	body_lord = 65,
	body_maceman = 66,
	body_man_burning = 67,
	body_mangonel = 68,
	body_miller = 69,
	body_missile_2 = 70,
	body_missile_cow = 71,
	body_missile = 72,
	body_missile_fire = 73,
	body_mother = 74,
	body_ox = 75,
	body_peasant = 76,
	body_pikeman = 77,
	body_pitch_worker = 78,
	body_poleturner = 79,
	body_priest = 80,
	body_rabbit = 81,
	body_seagull = 82,
	body_shield = 83,
	body_siege_engineer = 84,
	body_siege_tower = 85,
	body_spearman = 86,
	body_splash = 87,
	body_stonemason = 88,
	body_swordsman = 89,
	body_tanner = 90,
	body_tent = 91,
	body_trader = 92,
	body_trebutchet = 93,
	body_tunnelor = 94,
	body_wolf = 95,
	body_woodcutter = 96,
	tree_apple = 97,
	tree_birch = 98,
	tree_chestnut = 99,
	tree_oak = 100,
	tree_pine = 101,
	tree_shrub1 = 102,
	tree_shrub2 = 103
};

enum class TilesetID {
	killing_pits = 0,
	pitch_ditches = 1,
	tile_buildings1 = 2,
	tile_buildings2 = 3,
	tile_burnt = 4,
	tile_castle = 5,
	tile_churches = 6,
	tile_data = 7,
	tile_farmland = 8,
	tile_flatties = 9,
	tile_goods = 10,
	tile_land3 = 11,
	tile_land8 = 12,
	tile_land_and_stones = 13,
	tile_land_macros = 14,
	tile_rocks8 = 15,
	tile_ruins = 16,
	tile_sea8 = 17,
	tile_sea_new_01 = 18,
	tile_workshops = 19
};
enum class GenericImageID {
	anim_buildings2 = 0,
	anim_campaign_map_flags = 1,
	anim_castle = 2,
	anim_dancing_bear = 3,
	anim_dog_cage = 4,
	anim_drawbridge = 5,
	anim_ducking_stool = 6,
	anim_gallows = 7,
	anim_gibbet = 8,
	anim_goods = 9,
	anim_heads = 10,
	anim_killing_pits = 11,
	anim_rack = 12,
	anim_stocks = 13,
	anim_tunnelors_guild = 14,
	anim_whitecaps = 15,
	army_units = 16,
	blast3 = 17,
	body_brazier = 18,
	body_disease = 19,
	body_fire2 = 20,
	body_fire = 21,
	body_gate = 22,
	body_steam = 23,
	cracks = 24,
	cursors = 25,
	enemy_faces = 26,
	float_pop_circ = 27,
	floats = 28,
	floats_new = 29,
	font_slanted = 30,
	font_stronghold_aa = 31,
	font_stronghold = 32,
	icons_front_end_builder = 33,
	icons_front_end_combat = 34,
	icons_front_end = 35,
	icons_front_end_economics = 36,
	icons_placeholders = 37,
	interface_army = 38,
	interface_buttons = 39,
	interface_icons2 = 40,
	interface_icons3 = 41,
	interface_ruins = 42,
	interface_slider_bar = 43,
	mapedit_buttons = 44,
	mini_cursors = 45,
	oil_dropped = 46,
	rock_chips = 47,
	scribe = 48,
	smoke_30x30 = 49,
	tile_chevrons = 50,
	tile_cliffs = 51,
	tile_rocks_chevrons = 52,
	tile_walls = 53
};

constexpr size_t k_num_animation_assets =
    sizeof(animation_assets) / sizeof(AssetName);
constexpr size_t k_num_tile_assets = sizeof(tile_assets) / sizeof(AssetName);
constexpr size_t k_num_generic_image_assets = 0;
constexpr size_t k_num_graphics_assets =
    k_num_animation_assets + k_num_tile_assets + k_num_generic_image_assets;

constexpr size_t mapAssetToIndex(AnimationID id)
{
	return static_cast<size_t>(id);
}
constexpr size_t mapAssetToIndex(TilesetID id)
{
	return static_cast<size_t>(id);
}
constexpr size_t mapAssetToIndex(GenericImageID id)
{
	return static_cast<size_t>(id);
}

}  // namespace assets

}  // namespace castlekeep
#endif
